import { describe, it, expect } from "vitest";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, resolve } from "node:path";

const appDir = resolve(__dirname);

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (entry === "node_modules" || entry === "coverage") continue;
      walk(full, out);
    } else if (/\.(tsx?|css|mdx?)$/.test(entry)) {
      out.push(full);
    }
  }
  return out;
}

const forbidden = [
  /create next app/i,
  /generated by create next app/i,
  /vercel logomark/i,
];

describe("GF-12: no scaffold boilerplate in app/**", () => {
  const files = walk(appDir).filter((f) => !/\.test\.(tsx?|css)$/.test(f));

  it.each(files)("%s has no scaffold boilerplate", (file) => {
    const text = readFileSync(file, "utf8");
    for (const re of forbidden) {
      expect(text).not.toMatch(re);
    }
  });
});
